import { replenishList } from "./../../util/tool";
export const obj = {
  getData() {
    return {
      key2_2: [
        {
          xm: "分级护理表质量",
          zlhgf: "合格分90分",
          hgl: ">=90%",
          hgsccs: "9/10",
          pjf: "92",
          hgl2: "93%",
          wdb: "达标",
        },
        {
          xm: "分级护理表质量",
          zlhgf: "合格分90分",
          hgl: ">=90%",
          hgsccs: "9/10",
          pjf: "92",
          hgl2: "93%",
          wdb: "达标",
        },
        {
          xm: "分级护理表质量",
          zlhgf: "合格分90分",
          hgl: ">=90%",
          hgsccs: "9/10",
          pjf: "92",
          hgl2: "93%",
          wdb: "达标",
        },
        {
          xm: "分级护理表质量",
          zlhgf: "合格分90分",
          hgl: ">=90%",
          hgsccs: "9/10",
          pjf: "92",
          hgl2: "93%",
          wdb: "达标",
        },
        {
          xm: "分级护理表质量",
          zlhgf: "合格分90分",
          hgl: ">=90%",
          hgsccs: "9/10",
          pjf: "92",
          hgl2: "93%",
          wdb: "达标",
        },
      ],
      key2_3: {
        conclusion: {
          zb: 100,
          db: 80,
          wdb: 20,
        },
        tableData: [
          {
            zb: "护理指标高评分",
            zywt: "护理部门主要问题是红红火火恍恍惚惚或",
            yyfx: "原因分析原因分析原因分析哈哈哈",
            zgcs: "整改护理部署的措施",
            xgpj: "满意满意继续努力",
          },
          {
            zb: "护理指标高评分",
            zywt: "护理部门主要问题是红红火火恍恍惚惚或",
            yyfx: "原因分析原因分析原因分析哈哈哈",
            zgcs: "整改护理部署的措施",
            xgpj: "满意满意继续努力",
          },
          {
            zb: "护理指标高评分",
            zywt: "护理部门主要问题是红红火火恍恍惚惚或",
            yyfx: "原因分析原因分析原因分析哈哈哈",
            zgcs: "整改护理部署的措施",
            xgpj: "满意满意继续努力",
          },
        ],
      },
      key3_3: [
        { zlxm: "（一）分级护理（含基础护理、危重护理、围术期护理等）", zywt: "操作不熟练，操作时间慢123123", yyfx: '护士入职时间短,需加强培训', xgpj: "" },
        { zlxm: "（二）优质护理与人文关怀质量（含整体护理、健康教育、人文关怀、老年护理等）", zywt: "操作不熟练，操作时间慢", yyfx: '护士入职时间短,需加强培训', xgpj: "" },
        { zlxm: "（三）专科护理（含引流管护理、气道护理、专科仪器操作）", zywt: "操作不熟练，操作时间慢", yyfx: '护士入职时间短,需加强培训', xgpj: "" },
        { zlxm: "（四）导管相关护理（PIVC、CVC、PICC/MC）", zywt: "操作不熟练，操作时间慢", yyfx: '护士入职时间短,需加强培训', xgpj: "" },
        { zlxm: "（五）护理文件书写", zywt: "操作不熟练，操作时间慢", yyfx: '护士入职时间短,需加强培训', xgpj: "" },
        { zlxm: "（六）消毒隔离", zywt: "操作不熟练，操作时间慢", yyfx: '护士入职时间短,需加强培训', xgpj: "" },
        { zlxm: "（七）护理安全管理（一）（二）", zywt: "操作不熟练，操作时间慢", yyfx: '护士入职时间短,需加强培训', xgpj: "" },
        { zlxm: "（八）科室综合管理质量", zywt: "操作不熟练，操作时间慢", yyfx: '护士入职时间短,需加强培训', xgpj: "" },
        { zlxm: "（九）预防住院患者压力性损伤护理质量", zywt: "操作不熟练，操作时间慢", yyfx: '护士入职时间短,需加强培训', xgpj: "" },
        { zlxm: "（十）预防住院患者跌倒/坠床护理质量", zywt: "操作不熟练，操作时间慢", yyfx: '护士入职时间短,需加强培训', xgpj: "" },
        { zlxm: "（十一）疫情常态化管理", zywt: "操作不熟练，操作时间慢", yyfx: '护士入职时间短,需加强培训', xgpj: "" },
        { zlxm: "", zywt: "", yyfx: '', xgpj: "" },
      ],
      "4_4": {
        q: "question",
        r: {
          r: "人",
          j: "机",
          w: "物",
          f: "法",
          h: "环",
        },
        mr: "mainReason",
        sign: "目标",
        what: "what",
        why: "Why",
        how: "How",
        when: "When",
        where: "Where",
        who: "Who",
        c: "content",
      },
      "4_7": [
        {
          deptName: "",
          empName: "",
          score: "",
          mq: "",
        },
      ],
      report: {
        key1_1: "2",
        key2_1: "2",
        key2_2: "2",
        key2_3: "2",
        key4_8: "2",
        key5_1: "2",
        key5_2: "1",
      },
      fieldData: {
        ultQuestion: '',
        improveFeedback: '',
        monthWorkPlan: "",
        trainingPlanOfTheMonth: "",
        monthWorkDoneCase: "",
        monthTrainDoneCase: "",
        nurseCount: "",
        actualNurseCount: "",
        assistantNurseCount: "",
        actualInternNurseCount: "",
        actualDutyNursesCount: "",
        actualDutyInternNurseCount: "",
        averageBedOccupancy: "",
        bedTurnovers: "",
        deptAverageInDepartment: "",
        existingPatientCount: "",
        admissions: "",
        transferredPatientCount: "",
        dischargedPeopleCount: "",
        transferredOutPatientCount: "",
        deathToll: "",
        interventionalProcedureCount: "",
        numberOfSurgicalOperations: "",
        deptNursingWorkloadScore: "",
        cmi: "",
        lowRiskMortality: "",
        specialEventSolvedProblem: "",
        livePictures: "",
        deptWorkPlanForNextMonth: "",
        nextMonthDeptTrainingPlan: "",
        reportAdverseEvents: "",
        eventTypeAndLevel: "",
        overallIndicator: "",
        standardIndicators: "",
        nonComplianceIndicators: "",
        rw1: "",
        rw2: "",
        causeAnalysisPeople: "",
        homeServiceRate: "",
        question: "",
        causeAnalysisMachine: "",
        causeAnalysisThing: "",
        causeAnalysisLaw: "",
        causeAnalysisRing: "",
        causeAnalysisQuestion: "",
        mainReason: "",
        setGoal: "",
        planPrincipal: "",
        planImplementationSite: "",
        planImplementationTime: "",
        planCountermeasures: "",
        planMainReason: "",
        planQuestion: "",
        implementation: "",
        effectConfirmed: "",
        standardizedContent: "",
      },
      pageData: {
        id: null,
        isDeleted: null,
        publisherName: "",
        publisherNo: "",
        publisherTime: "",
        renderTableDataMap: null,
        reportLevel: "",
        reportMonth: "",
        reportName: "",
        updateTime: "",
        updaterName: "",
        updaterNo: "",
        wardCode: "",
        wardName: "",
      }
    };
  },
  formatData() {
    (this as any).getSectionData("1_1").value = (this as any).allData.fieldData;
    (this as any).getSectionData("2_1").value = (this as any).allData.fieldData;
    (this as any).getSectionData("2_1").list = (this as any).allData["key2_1"];
    (this as any).getSectionData("2_2").list = (this as any).allData["key2_2"];
    (this as any).getSectionData("2_3").value = (this as any).allData.fieldData;
    (this as any).getSectionData("2_3").list = replenishList({data: (this as any).allData.tableDataMap, config: (this as any).configData, name: 'deptNotPassIndexImprove', len: 3});
    (this as any).getSectionData("3_1").value = (this as any).allData.fieldData;
    (this as any).getSectionData("3_1").list= {};
    (this as any).getSectionData("3_2").value = (this as any).allData.fieldData;
    (this as any).getSectionData("3_2").pageInfo= (this as any).allData.pageInfo;
    (this as any).getSectionData("3_3").value = (this as any).allData.fieldData;
    (this as any).getSectionData("3_5").value = (this as any).allData.fieldData;
    (this as any).getSectionData("5_1").value = (this as any).allData.fieldData;
    (this as any).getSectionData("5_2").value = (this as any).allData.fieldData;
  },
}
