const res = {
    "code": "200",
    "desc": "操作成功",
    "data": {
        "id": 320,
        "formCode": "E0616",
        "documentName": "GCS评估",
        "documentShowType": "列表",
        "description": "聊城市第二人民医院\r\nGlasgow昏迷评分(GCS)",
        "resultDescription": "备注:\r\n1、将三个项目得分相加，即得到GCS评分，。",
        "nooForm": "",
        "scoreFlag": "1",
        "documentHeads": [],
        "documentItemDtos": [
            {
                "id": 271,
                "formCode": "E0616",
                "sortValue": 1,
                "documentName": "睁眼反应",
                "documentTypeName": "",
                "documentDescription": "睁眼反应",
                "documentMaxScore": null,
                "nursingMeasure": "0",
                "documentRender": "竖显示",
                "documentSaveType": "",
                "module": "",
                "createTime": null,
                "description": "",
                "documentNameShow": "0",
                "documentUserSelect": "1",
                "documentItemLists": [
                    {
                        "id": 655,
                        "documentItemId": 271,
                        "name": "I616001",
                        "type": "radio",
                        "value": "自行睁眼",
                        "saveValue": "4",
                        "jsInteractive": "",
                        "appointment": "",
                        "prefixDescription": "",
                        "suffixDescription": "",
                        "expand": "",
                        "fatherStatu": "",
                        "score": 4,
                        "sortValue": 1,
                        "createTime": null,
                        "documentItemName": "",
                        "documentItemValue": "",
                        "attachmentId": null,
                        "documentItemLists": [],
                        "formRecordList": null,
                        "isSelected": false
                    },
                    {
                        "id": 656,
                        "documentItemId": 271,
                        "name": "I616001",
                        "type": "radio",
                        "value": "呼之睁眼",
                        "saveValue": "3",
                        "jsInteractive": "",
                        "appointment": "",
                        "prefixDescription": "",
                        "suffixDescription": "",
                        "expand": "",
                        "fatherStatu": "",
                        "score": 3,
                        "sortValue": 2,
                        "createTime": null,
                        "documentItemName": "",
                        "documentItemValue": "",
                        "attachmentId": null,
                        "documentItemLists": [],
                        "formRecordList": null,
                        "isSelected": false
                    },
                    {
                        "id": 657,
                        "documentItemId": 271,
                        "name": "I616001",
                        "type": "radio",
                        "value": "刺痛睁眼",
                        "saveValue": "2",
                        "jsInteractive": "",
                        "appointment": "",
                        "prefixDescription": "",
                        "suffixDescription": "",
                        "expand": "",
                        "fatherStatu": "",
                        "score": 2,
                        "sortValue": 3,
                        "createTime": null,
                        "documentItemName": "",
                        "documentItemValue": "",
                        "attachmentId": null,
                        "documentItemLists": [],
                        "formRecordList": null,
                        "isSelected": false
                    },
                    {
                        "id": 658,
                        "documentItemId": 271,
                        "name": "I616001",
                        "type": "radio",
                        "value": "无反应",
                        "saveValue": "1",
                        "jsInteractive": "",
                        "appointment": "",
                        "prefixDescription": "",
                        "suffixDescription": "",
                        "expand": "",
                        "fatherStatu": "",
                        "score": 1,
                        "sortValue": 4,
                        "createTime": null,
                        "documentItemName": "",
                        "documentItemValue": "",
                        "attachmentId": null,
                        "documentItemLists": [],
                        "formRecordList": null,
                        "isSelected": false
                    }
                ]
            },
            {
                "id": 272,
                "formCode": "E0616",
                "sortValue": 3,
                "documentName": "言语反应",
                "documentTypeName": "",
                "documentDescription": "言语反应",
                "documentMaxScore": null,
                "nursingMeasure": "0",
                "documentRender": "竖显示",
                "documentSaveType": "",
                "module": "",
                "createTime": null,
                "description": "",
                "documentNameShow": "0",
                "documentItemLists": [
                    {
                        "id": 659,
                        "documentItemId": 272,
                        "name": "I616002",
                        "type": "radio",
                        "value": "正确对答",
                        "saveValue": "5",
                        "jsInteractive": "",
                        "appointment": "",
                        "prefixDescription": "",
                        "suffixDescription": "",
                        "expand": "",
                        "fatherStatu": "",
                        "score": 5,
                        "sortValue": 1,
                        "createTime": null,
                        "documentItemName": "",
                        "documentItemValue": "",
                        "attachmentId": null,
                        "documentItemLists": [],
                        "formRecordList": null,
                        "isSelected": false
                    },
                    {
                        "id": 660,
                        "documentItemId": 272,
                        "name": "I616002",
                        "type": "radio",
                        "value": "回答错误",
                        "saveValue": "4",
                        "jsInteractive": "",
                        "appointment": "",
                        "prefixDescription": "",
                        "suffixDescription": "",
                        "expand": "",
                        "fatherStatu": "",
                        "score": 4,
                        "sortValue": 2,
                        "createTime": null,
                        "documentItemName": "",
                        "documentItemValue": "",
                        "attachmentId": null,
                        "documentItemLists": [],
                        "formRecordList": null,
                        "isSelected": false
                    }
                ]
            }
        ]
    },
    "errorCode": ""
}
export default res